const fs = require('fs');
const path = require('path');

const targetFlavour = process.argv[2];

if (!targetFlavour) {
  console.error("Usage: node build.js <flavour>");
  console.error("Available flavours: dev, qa, etc. (must match keys in flavours.json)");
  process.exit(1);
}

const flavoursPath = path.join(__dirname, 'flavours.json');
let flavours;
try {
  flavours = JSON.parse(fs.readFileSync(flavoursPath, 'utf8'));
} catch (e) {
  console.error("Error reading flavours.json:", e.message);
  process.exit(1);
}

const config = flavours[targetFlavour];
if (!config) {
  console.error(`Flavour '${targetFlavour}' not found in flavours.json.`);
  process.exit(1);
}

// Read from the requested flavour's entry in flavours.json - falls back to
// the qa URL only if that flavour has no baseurl set at all (missing tag),
// not as a blanket override regardless of flavour.
const rawBaseUrl = config.baseurl || "https://portal.qa.halofort.com";
const baseUrl = rawBaseUrl.endsWith('/') ? rawBaseUrl.slice(0, -1) : rawBaseUrl;

let apiUrl, authUrl, authLoginUrl;

if (config.useCollectorApi) {
  // Production environments route to the new HaloFort collector endpoint and its custom auth endpoint
  apiUrl = `${baseUrl}/collector/v1/events/location_v1`;
  authUrl = `${baseUrl}/chromeos/v1/devicefeedback/{deviceId}?app=launcher`;
  authLoginUrl = `${baseUrl}/idm/v1/auth/feedback/login`;
} else {
  // Local development routes to the local Go backend (which doesn't require auth anymore)
  apiUrl = `${baseUrl}/api/chromeos/location`;
  authUrl = "";
  authLoginUrl = "";
}

const configJsContent = `// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by build.js for flavour: ${targetFlavour}

export const USE_COLLECTOR_API = ${!!config.useCollectorApi};
export const TENANT_ID = "${config.tenantId || ''}";
export const API_URL = "${apiUrl}";
export const AUTH_URL = "${authUrl}";
export const AUTH_LOGIN_URL = "${authLoginUrl}";
`;

fs.writeFileSync(path.join(__dirname, 'config.js'), configJsContent);
console.log(`Successfully built config.js for flavour '${targetFlavour}'.`);
