// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by build.js for flavour: qa

export const USE_COLLECTOR_API = true;
export const TENANT_ID = "";
export const API_URL = "https://portal.qa.halofort.com/collector/v1/events/location_v1";
export const AUTH_URL = "https://portal.qa.halofort.com/chromeos/v1/devicefeedback/{deviceId}?app=launcher";
export const AUTH_LOGIN_URL = "https://portal.qa.halofort.com/idm/v1/auth/feedback/login";
