// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by build.js for flavour: local

export const USE_COLLECTOR_API = false;
export const TENANT_ID = "";
export const API_URL = "http://192.168.21.143:8080/api/chromeos/location";
export const AUTH_URL = "";
export const AUTH_LOGIN_URL = "";
